# Generated by Django 4.2.2 on 2023-07-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('work_status', models.CharField(max_length=100, verbose_name='Должность')),
                ('start_work_time', models.TimeField(auto_now=True, verbose_name='День приема на работу')),
                ('salary', models.IntegerField(verbose_name='Зар. Плата')),
                ('boss', models.CharField(max_length=50, verbose_name='Начальник')),
            ],
        ),
    ]
